#!/usr/bin/env bash
set -e
# Auto-generated by cerchi_concentrici — 4 livello/i

cd "/Users/samuele/Progetti/QUADRI/GENERATIVE/vsketch"
LATEST_SVG=$(ls -t examples/cerchi_concentrici/output/*.svg | head -1)
echo "Using SVG: $LATEST_SVG"

./svg2gcode.sh "$LATEST_SVG" 0.0 5.1 3000 500 700 0

# Insert M0; before each layer boundary (except the first)
GCODE="${LATEST_SVG%.svg}.gcode"
awk 'BEGIN{first=1} /^; --- Layer /{if(!first){print "M0;"} first=0} {print}' "$GCODE" > "${GCODE}.tmp" && mv "${GCODE}.tmp" "$GCODE" 
echo "M0; pause inserted between layers"

echo "Done!"
